#https://www.youtube.com/watch?v=w-X_EQ2Xva4&t=485s&ab_channel=TechWorldwithNana
#To run in command prompt type "python3 python-chatgpt.py "Prompt" "FileName""
import requests
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument("prompt", help="The prompt to send to the OpenAI API")
parser.add_argument("file_name", help="Name of the file to save Python script")
args = parser.parse_args()

api_endpoint = "https://api.openai.com/v1/completions"
api_key=os.getenv("OPEN_API_KEY")

request_headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer "+ api_key
}
request_data ={
    "model": "text-davinci-003",
    "prompt": f"Write Python script to {args.prompt}",
    #Number of character generated by chatGPT
    "max_tokens": 800,
    #Creativity of the request 0 not creative 1 very creative
    "temperature": 0.5
}
response = requests.post(api_endpoint, headers=request_headers, json=request_data)

if response.status_code == 200:
    response_text = response.json()["choices"][0]["text"]
    with open(args.file_name,"w") as file:
        file.write(response_text)
    print("Done!")
else:
    print(f"Request failed with status code: {str(response.status_code)}")